<!DOCTYPE html>
<html>
    <head>
        <title>JRouter About</title>
        <meta name="keywords" content="JRouter About 关于" />
        <meta name="description" content="JRouter About 关于" />
        [@template.header/]
    </head>
    <body>
        [@template.body navbar="about"]
        <div class="row">
            <div class="blog-header">
            </div>
            <div class="col-sm-10 blog-main">
                <div class="blog-post">
                    <h2>About 关于</h2>
                    <hr>
                    <p style="padding-left: 50px">
                        <img src="${base}/img/architecture.gif" title="有一个架构图" alt="有一个机器人"/>
                    </p>
                    <p>
                    </p>
                </div><!-- /.blog-post -->
            </div><!-- /.blog-main -->
        </div><!-- /.row -->
        [/@template.body]
        [@template.footer/]
    </body>
</html>
